title: CLEAN CODER
description: 程序袁CC
keywords: sjyuan,blog,Jekyll,github
baseurl: ""
permalink: /:title/
url: https://sjyuan.cc
img_path: /assets/images

junit:
  current_version: 5.3.0

author:
  name: Yuan Shenjian
  first_name: Shenjian
  last_name: Yuan
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: sjyuan-cc
  linkedin_id:
  facebook_username:
  twitter_username:
  email: sjyuan@thoughtworks.com
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now

# comment
gitment:
  owner: sjyuan-cc
  repo: sjyuan-cc.github.io
  oauth:
    client_id: 7496a0eec255a36f5c0c
    client_secret: 7a917626d8eee8782f47ec4d09d601f2f9d9285c

encoding: utf-8

# other settings
#highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: assets/_sass
  style: compressed

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all
