title: Home
description: 袁慎建的博客
keywords: sjyuan,blog,Jekyll,github
baseurl: ""
permalink: /:title/
url: https://yuanshenjian.cn
img_path: /assets/images
image_path_post: /assets/images/post
is_personal: true


junit:
  current_version: 5.3.0

author:
  name: 袁慎建
  first_name: Shenjian
  last_name: Yuan
  avatar: /static/assets/img/landing/avatar.jpg
  github_username: yuanshenjian
  linkedin_id:
  facebook_username:
  twitter_username:
  jianshu: https://www.jianshu.com/u/c379cdabd121/
  yuque: https://www.yuque.com/yuanshenjian/
  xpbootcamp: https://xpbootcamp.cn
  email: sjyuan@thoughtworks.com
  cv:   # A online CV can be printed as PDF, leave blank if you don't have now

encoding: utf-8

# other settings
#highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: assets/_sass
  style: compressed

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all

gitalk:
  clientID: '0b21881f88d50f192dd2'
  clientSecret: '0ef973c404b0680248f396ee59be3492adcc1e07'
  repo: 'yuanshenjian.github.io'
  owner: 'yuanshenjian'
  admin: ['yuanshenjian']
