
catetories:
  - name: 学习目标
    articles:
      - title: 编写培训目标的ABCD模式
        link: https://www.jianshu.com/p/c1856cb1e6d2
      - title: 制定学习目标的SMART原则
        link: https://www.jianshu.com/p/c405c7464265
  - name: 破冰游戏
    articles:
      - title: 江湖名客
        link: https://www.jianshu.com/p/3665bf65e76c
      - title: 悠悠记者
        link: https://www.jianshu.com/p/4191ddb22329
      - title: 双枪老太婆
        link: https://www.jianshu.com/p/22e09fa25c14
      - title: 能量嘿传
        link: https://www.jianshu.com/p/0d9d7e723fda
